INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('2', 'imag/palabras/hola.png', 'Hola', 'Adiós', 'Buen día', 'Buenas noches');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('2', 'imag/palabras/adios.png', 'Adiós', 'Buen día', 'Buenas noches', 'Gracias');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('2', 'imag/palabras/buen_dia.png', 'Buen día', 'Buenas noches', 'Gracias', 'Por favor');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('2', 'imag/palabras/buenas_noches.png', 'Buenas noches', 'Gracias', 'Por favor', 'Mamá');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('2', 'imag/palabras/gracias.png', 'Gracias', 'Por favor', 'Mamá', 'Papá');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('2', 'imag/palabras/por_favor.png', 'Por favor', 'Mamá', 'Papá', 'Hermano');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('2', 'imag/palabras/mama.png', 'Mamá', 'Papá', 'Hermano', 'Hermana');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('2', 'imag/palabras/papa.png', 'Papá', 'Hermano', 'Hermana', 'Abuelo');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('2', 'imag/palabras/hermano.png', 'Hermano', 'Hermana', 'Abuelo', 'Hijo');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('2', 'imag/palabras/hermana.png', 'Hermana', 'Abuelo', 'Hijo', 'Uno');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('2', 'imag/palabras/abuelo.png', 'Abuelo', 'Hijo', 'Uno', 'Dos');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('2', 'imag/palabras/hijo.png', 'Hijo', 'Uno', 'Dos', 'Tres');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('2', 'imag/palabras/uno.png', 'Uno', 'Dos', 'Tres', 'Cuatro');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('2', 'imag/palabras/dos.png', 'Dos', 'Tres', 'Cuatro', 'Cinco');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('2', 'imag/palabras/tres.png', 'Tres', 'Cuatro', 'Cinco', 'Diez');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('2', 'imag/palabras/cuatro.png', 'Cuatro', 'Cinco', 'Diez', 'Hola');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('2', 'imag/palabras/cinco.png', 'Cinco', 'Diez', 'Hola', 'Adiós');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('2', 'imag/palabras/diez.png', 'Diez', 'Hola', 'Adiós', 'Buen día');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('3', 'imag/frases/nombre.png', '¿Cuál es tu nombre?', 'De nada', 'Ayuda', 'Lo siento');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('3', 'imag/frases/de_nada.png', 'De nada', 'Ayuda', 'Lo siento', 'Tengo sed');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('3', 'imag/frases/ayuda.png', 'Ayuda', 'Lo siento', 'Tengo sed', 'Con permiso');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('3', 'imag/frases/lo_siento.png', 'Lo siento', 'Tengo sed', 'Con permiso', '¿De dónde eres?');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('3', 'imag/frases/sed.png', 'Tengo sed', 'Con permiso', '¿De dónde eres?', '¿Cuánto cuesta?');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('3', 'imag/frases/con_permiso.png', 'Con permiso', '¿De dónde eres?', '¿Cuánto cuesta?', 'Estoy enfermo');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('3', 'imag/frases/de_donde.png', '¿De dónde eres?', '¿Cuánto cuesta?', 'Estoy enfermo', 'Me gusta');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('3', 'imag/frases/cuanto_cuesta.png', '¿Cuánto cuesta?', 'Estoy enfermo', 'Me gusta', '¿Cuál es tu nombre?');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('3', 'imag/frases/enfermo.png', 'Estoy enfermo', 'Me gusta', '¿Cuál es tu nombre?', 'De nada');
INSERT INTO Pregunta (id_Modulo, imagen, respuesta_correcta, opcion1, opcion2, opcion3) VALUES ('3', 'imag/frases/me_gusta.png', 'Me gusta', '¿Cuál es tu nombre?', 'De nada', 'Ayuda');
